###https://love-comic-api.herokuapp.com/api/
POST https://love-comic-api.herokuapp.com/api/register
content-type: application/json

{
    "user_email": "huyson201@gmail.com",
    "user_password": "asdasd",
    "confirm_password": "asdasd",
    "user_name": "huy son"
   
}

###
POST http://localhost:3001/api/login
content-type: application/json 

{
    "user_email" :"huyson201@gmail.com",
    "user_password": "asdasd"
}

### logout
POST http://localhost:3001/api/logout
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIzMDQ3OGM1Yi1kZTFiLTQ5YmEtODFjNC1kZTg4ZTBjMTQxNGIiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwMUBnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0yOFQxMzoxNTo0NS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0yOFQxMzoxNTo0NS4wMDBaIiwiaWF0IjoxNjM1NDI2OTU0LCJleHAiOjE2MzU0MzQxNTR9.iX4BM7MFbxWB1dE5U8b4YRlJXX-3XwQzAtx6mqQSVU4

### refresh token
POST http://localhost:3001/api/refresh-token
content-type: application/json 

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI4ZjdhM2E2Ni1iZjA2LTRiMDAtOTBlMC0yOTVlZTg0YTZlYjYiLCJpYXQiOjE2MzU1NzQwNTksImV4cCI6MTYzNjE3ODg1OX0.pUE3VM6vAIRrmhC-8ptb4JeqaDv5Y7ULfY7PTU5dlLg"
}

### get detail users
GET http://localhost:3001/api/users/9aeff779-df69-4b4b-ada2-bd568ea751e1
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI3Y2Y4MWE2Ni1mYjZlLTQyNmEtYmIyOC1jZmI3MDkyYjg2NDgiLCJ1c2VyX25hbWUiOiJNcy4gTWlsdG9uIEJhaHJpbmdlciIsInVzZXJfZW1haWwiOiJSb3J5LlVwdG9uNjhAeWFob28uY29tIiwidXNlcl9pbWFnZSI6ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBT0VBQUFEaENBTUFBQUFKYlNKSUFBQUFiMUJNVkVYLy8vOEFBQUNLaW9ybTV1Wi9mMy9zN096WjJkbGhZV0dFaElTSGg0Zmg0ZUh5OHZLQ2dvTEh4OGYxOWZWNWVYbGNYRnlnb0tCSVNFaSt2cjZ3c0xBVEV4TW1KaWFUazVNYkd4dERRME0wTkRSVFUxTnpjM1BTMHRLdHJhMmJtNXN0TFMwaUlpSk9UazY2dXJwcmEydTlsUWsrQUFBRlZrbEVRVlI0bk8yZGkxcmlRQXhHRyIsInVzZXJfcm9sZSI6InVzZXIiLCJpYXQiOjE2MzU2NTk1NjMsImV4cCI6MTYzNTY2Njc2M30.F1nPtNwgCH7Wuw_6JzsQff7igjPxZwVY1dejVTnQVNI

### update user
PATCH http://localhost:3001/api/users/
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI4ZjdhM2E2Ni1iZjA2LTRiMDAtOTBlMC0yOTVlZTg0YTZlYjYiLCJ1c2VyX25hbWUiOiJzb24gMTIzIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwMUBnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjoiIiwidXNlcl9yb2xlIjoiYWRtaW4iLCJpYXQiOjE2MzU2NTU4NjMsImV4cCI6MTYzNTY2MzA2M30.3kK4KVkPi08qkJUaKIh2V3YQidj7nC7SvxQ478ue4E8

{
    "user_name": "son 123"
}

### get comics of category
GET http://localhost:3001/api/categories
content-type: application/json 


### create rating
POST http://localhost:3001/api/rates
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI1NjNlMGI4ZS02ZWFiLTQxZWEtOTUxYi0yYzVkZGJhMDE4NjQiLCJ1c2VyX25hbWUiOiJuZ29jMzQiLCJ1c2VyX2VtYWlsIjoibmdvYzJAZ21haWwuY29tIiwidXNlcl9pbWFnZSI6Im51bGwiLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0yMlQxNToxNDo0NC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0yM1QwNzoxMjo0My4wMDBaIiwiaWF0IjoxNjM0OTczODI5LCJleHAiOjE2MzQ5ODEwMjl9.kIMhxrnloACGrRnvCP8Cu_FDscUCYMNp3PVl8xSzTnQ

{
    "rate_star" : 4,
    "comic_id": 1
}

### get rate by user id and comic_id
GET http://localhost:3001/api/rates?comic_id=1

### calculate sum rate of comic
GET http://localhost:3001/api/rates/sum?comic_id=1

### update rate have id = 1
PATCH http://localhost:3001/api/rates/1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI4ZjdhM2E2Ni1iZjA2LTRiMDAtOTBlMC0yOTVlZTg0YTZlYjYiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImlhdCI6MTYzNTY2NDQyMCwiZXhwIjoxNjM1NjcxNjIwfQ.36mhMh_iumFfwUCO6tX_PPDg9MuBQAQ_9eOUMo8EINI

{
    "user_uuid": "8f7a3a66-bf06-4b00-90e0-295ee84a6eb6",
    "rate_star": 5
}

### change password
patch http://localhost:3001/api/users/change-password
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI5Yzc1MjZmNy1jYzIyLTQyMzMtYmE4NC0xNzFiNDdjNDY0MzIiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwMUBnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0yOFQxMzo0NTozMC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0yOFQxMzo0NTozMC4wMDBaIiwiaWF0IjoxNjM1NDI4NzM1LCJleHAiOjE2MzU0MzU5MzV9.PaYtFugykZmIi2ydnS63ZmVxO5SNiF2c4JY974OiZeU

{
   "old_password": "asdasd",
   "new_password": "asdasd123"
}


### get follows
GET http://localhost:3001/api/follows

### get follows by user_uuid, comic-id
GET http://localhost:3001/api/follows?user_uuid=1e69aa36-db41-454b-99e9-2c07f11eaa8f&comic_id=2



### create follow

POST http://localhost:3001/api/follows
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIyOTViYjc5Yi1jODZiLTQ1ZGUtODViNi0zODE4MzBkZmYxZWMiLCJ1c2VyX25hbWUiOiJuZ29jMyIsInVzZXJfZW1haWwiOiJuZ29jMkBnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwODowOTozMi4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNlQwNzowNToxNS4wMDBaIiwiaWF0IjoxNjM0ODY5MzIxLCJleHAiOjE2MzQ4NzY1MjF9.9wpiGBjSCrgAh3aw9xhul0irdy8Xi-TIDoHCaGdjF_4

{
    "comic_id": 1
}

### delete a follow
DELETE  http://localhost:3001/api/follows
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNVQwMToyNDo0Ni4wMDBaIiwiaWF0IjoxNjM0MzA0MDA3LCJleHAiOjE2MzQzMTEyMDd9.mRBHtphdpi76ooCQDdPpfySkcNwB2jfglh6PeDOsD1c

{
   "follow_id": 4
}


### create a comment
POST  http://localhost:3001/api/comments
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNVQwMToyNDo0Ni4wMDBaIiwiaWF0IjoxNjM0MzA0MDA3LCJleHAiOjE2MzQzMTEyMDd9.mRBHtphdpi76ooCQDdPpfySkcNwB2jfglh6PeDOsD1c

{
   "comic_id": 1,
   "comment_content": "comment content...",
   "parent_id": 2

}


### get all comment
GET  http://localhost:3001/api/comments
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNVQwMToyNDo0Ni4wMDBaIiwiaWF0IjoxNjM0MzA0MDA3LCJleHAiOjE2MzQzMTEyMDd9.mRBHtphdpi76ooCQDdPpfySkcNwB2jfglh6PeDOsD1c

{
   "comic_id": 1,
   "comment_content": "comment content...",
   

}

### get comments of comic
GET http://localhost:3001/api/comics/1/comments?offset=2&limit=1&sort=updatedAt:desc

### admin 
GET http://localhost:3001/api/admin/comics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJuZ3V5ZW4gZG9hbiBodXkgc29uICIsInVzZXJfZW1haWwiOiJodXlzb24yMDNAZ21haWwuY29tIiwidXNlcl9pbWFnZSI6Imh0cHA6Ly9sb2NhbGhvc3Q6MzAwMS9pbWFnZXMvZTdlNDA2ZDIxNjZjYmVmNzExZTNmNGQ0ZGYwZWM3ZGYiLCJ1c2VyX3JvbGUiOiJhZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjEtMTAtMTRUMDQ6MTY6NTEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjEtMTAtMjFUMTI6MjQ6MDMuMDAwWiIsImlhdCI6MTYzNDgyMTE4OCwiZXhwIjoxNjM0ODI4Mzg4fQ.L0JNBJD7BdvhGTy7XyrxAYqhzGn5eh6r_1vw2FyxkK4

###https://love-comic-api.herokuapp.com/api/
POST https://love-comic-api.herokuapp.com/api/forget-password
Content-Type:  application/json

{
    "user_email": "huyson201@gmail.com"
}

### 
POST http://localhost:3001/api/forget-password/confirm
Content-Type:  application/json

{
    "reset_password_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAzQGdtYWlsLmNvbSIsInVzZXJfcm9sZSI6ImFkbWluIiwiaWF0IjoxNjM0ODcyNjk3LCJleHAiOjE2MzQ4NzI3Mjd9.AdPQE9LwpDfbNAupLTFs2A69apUGIPf3WiSdV00coLM"
}

###
POST http://localhost:3001/api/reset-password
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX2VtYWlsIjoiaHV5c29uMjAzQGdtYWlsLmNvbSIsInVzZXJfcm9sZSI6ImFkbWluIiwiaWF0IjoxNjM0ODcyNjk3LCJleHAiOjE2MzQ4NzI3Mjd9.AdPQE9LwpDfbNAupLTFs2A69apUGIPf3WiSdV00coLM

{
    "new_password": "son123",
    "confirm_password": "son123"
}