POST http://localhost:3001/api/register
content-type: application/json

{
    "user_email": "huyson203@gmail.com",
    "user_password": "asdasd",
    "confirm_password": "asdasd",
    "user_name": "huy son"
   
}

###
POST http://localhost:3001/api/login
content-type: application/json 

{
    "user_email" :"huyson203@gmail.com",
    "user_password": "asdasd"
}

### refresh token
POST http://localhost:3001/api/refresh-token
content-type: application/json 

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIzMjY1NWFkYy03MTQ1LTRhNWYtODBjNy00MzFmNDJlMTg1MzkiLCJ1c2VyX25hbWUiOiJLaeG7gXUgT2FuaCIsInVzZXJfZW1haWwiOiJsdXV0aGlraWV1b2FuaEBnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xM1QxMDoyODozOS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xM1QxMDo1MDoyMC4wMDBaIiwiaWF0IjoxNjM0MTIyNDEyLCJleHAiOjE2MzQ3MjcyMTJ9.PwOLs7sj_lKX_9pfVw8AvMG_c51tNizmxhe39TXR8Es"
}

### get detail users
GET http://localhost:3001/api/users/6dc4f2b8-24e4-4a63-b2fd-3a9d72c8e706
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI2ZGM0ZjJiOC0yNGU0LTRhNjMtYjJmZC0zYTlkNzJjOGU3MDYiLCJ1c2VyX25hbWUiOiJOZ3V5ZW4gRG9hbiBIdXkgU29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNFQwMzoyNjoxMy4wMDBaIiwiaWF0IjoxNjM0MTgxOTg4LCJleHAiOjE2MzQxODkxODh9.E31aAiRlhdkCbQOqy9Nf1CmtFqRxlq92IDurTw3T12Q


### update user
PATCH http://localhost:3001/api/users/
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI2ZGM0ZjJiOC0yNGU0LTRhNjMtYjJmZC0zYTlkNzJjOGU3MDYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwiaWF0IjoxNjM0MTc5OTQzLCJleHAiOjE2MzQxODcxNDN9.swZ6n6HFzMC3GPSX2wOqQ72g079ROJhaue1tC9NcBwM

{
    "user_name": "Nguyen Doan Huy Son",
}

### get comics of category
GET http://localhost:3001/api/categories/2/comics
content-type: application/json 

### create rating
POST http://localhost:3001/api/rates
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwiaWF0IjoxNjM0MjYxMDg2LCJleHAiOjE2MzQyNjgyODZ9.qTWCgn2OGpxltXy9aIFf2wySfHKX5-U9TgpIIT21LN8

{
    "rate_star" : 5,
    "comic_id": 1
}


### change password
patch http://localhost:3001/api/users/change-password
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI2ZGM0ZjJiOC0yNGU0LTRhNjMtYjJmZC0zYTlkNzJjOGU3MDYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwiaWF0IjoxNjM0MTc5OTQzLCJleHAiOjE2MzQxODcxNDN9.swZ6n6HFzMC3GPSX2wOqQ72g079ROJhaue1tC9NcBwM

{
   "old_password": "asdasd",
   "new_password": "asdasd123"
}

### create follow

POST http://localhost:3001/api/follows
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNVQwMToyNDo0Ni4wMDBaIiwiaWF0IjoxNjM0MzA0MDA3LCJleHAiOjE2MzQzMTEyMDd9.mRBHtphdpi76ooCQDdPpfySkcNwB2jfglh6PeDOsD1c

{
    "comic_id": 3
}

### delete a follows
DELETE  http://localhost:3001/api/follows
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNVQwMToyNDo0Ni4wMDBaIiwiaWF0IjoxNjM0MzA0MDA3LCJleHAiOjE2MzQzMTEyMDd9.mRBHtphdpi76ooCQDdPpfySkcNwB2jfglh6PeDOsD1c

{
   "follow_id": 4
}


### create a comment
POST  http://localhost:3001/api/comments
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNVQwMToyNDo0Ni4wMDBaIiwiaWF0IjoxNjM0MzA0MDA3LCJleHAiOjE2MzQzMTEyMDd9.mRBHtphdpi76ooCQDdPpfySkcNwB2jfglh6PeDOsD1c

{
   "comic_id": 1,
   "comment_content": "comment content...",
   "parent_id": 2

}


### get all comment
GET  http://localhost:3001/api/comments
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIxZTY5YWEzNi1kYjQxLTQ1NGItOTllOS0yYzA3ZjExZWFhOGYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwNDoxNjo1MS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNVQwMToyNDo0Ni4wMDBaIiwiaWF0IjoxNjM0MzA0MDA3LCJleHAiOjE2MzQzMTEyMDd9.mRBHtphdpi76ooCQDdPpfySkcNwB2jfglh6PeDOsD1c

{
   "comic_id": 1,
   "comment_content": "comment content...",
   

}

### get comments of comic
GET http://localhost:3001/api/comics/1/comments?offset=2&limit=1&sort=updatedAt:desc