POST http://localhost:3001/api/register
content-type: application/json

{
    "user_email": "huyson203@gmail.com",
    "user_password": "asdasd",
    "confirm_password": "asdasd",
    "user_name": "huy son"
   
}

###
POST http://localhost:3001/api/login
content-type: application/json 

{
    "user_email" :"huyson203@gmail.com",
    "user_password": "asdasd123"
}

### refresh token
POST http://localhost:3001/api/refresh-token
content-type: application/json 

{
    "refreshToken" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIyYTY2YWY4OC0yNmEwLTQ1NDYtYjQxOS1jZTY1OWViN2U3OTYiLCJ1c2VyX25hbWUiOiJMxrB1IFRo4buLIEtp4buBdSBPYW5oIiwidXNlcl9lbWFpbCI6Imx1dXRoaWtpZXVvYW5oQGdtYWlsLmNvbSIsInVzZXJfaW1hZ2UiOm51bGwsInVzZXJfcm9sZSI6InVzZXIiLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTEyVDEzOjQxOjA1LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTEwLTEyVDE1OjExOjA5LjAwMFoiLCJpYXQiOjE2MzQwNTE1MDUsImV4cCI6MTYzNDY1NjMwNX0.LAfceUYYUb48eIExlgF1mbYww-imF8z2lFUeCAHBRvg"
}

### update user
PATCH http://localhost:3001/api/users/
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI2ZGM0ZjJiOC0yNGU0LTRhNjMtYjJmZC0zYTlkNzJjOGU3MDYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwiaWF0IjoxNjM0MTc5OTQzLCJleHAiOjE2MzQxODcxNDN9.swZ6n6HFzMC3GPSX2wOqQ72g079ROJhaue1tC9NcBwM

{
    "user_name": "Nguyen Doan Huy Son",
}

### get comics of category
GET http://localhost:3001/api/categories/2/comics
content-type: application/json 

### create rating
POST http://localhost:3001/api/rates
content-type: application/json 

{
    "rate_star" : 3,
    "user_uuid": "517be5df-feda-48db-a6c7-d12639a6718c",
    "comic_id": 1
}


### change password
patch http://localhost:3001/api/users/change-password
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI2ZGM0ZjJiOC0yNGU0LTRhNjMtYjJmZC0zYTlkNzJjOGU3MDYiLCJ1c2VyX25hbWUiOiJodXkgc29uIiwidXNlcl9lbWFpbCI6Imh1eXNvbjIwM0BnbWFpbC5jb20iLCJ1c2VyX2ltYWdlIjpudWxsLCJ1c2VyX3JvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0xMC0xNFQwMjo1MToyNC4wMDBaIiwiaWF0IjoxNjM0MTc5OTQzLCJleHAiOjE2MzQxODcxNDN9.swZ6n6HFzMC3GPSX2wOqQ72g079ROJhaue1tC9NcBwM

{
   "old_password": "asdasd",
   "new_password": "asdasd123"
}